### ISSUE TITLE
Clean up and enhance test.py

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#104]
The test.py file in the root directory of the repo contains a bunch of code that I use for testing. Some of it is just calling an RPC and printing the output, some call several RPCs, some functions do some basic perf testing, some do basic verification, etc. It's not properly maintained or documented though. We should clean it up and document it, and I would like if we could add A/B testing to it, where the script makes a request to clio and then a request to rippled and compares the output. This way everyone can test their code. The c++ unit tests only test the backend, not the handlers.

**Comment by godexsoft** [comment]
We should fix RPC and everything else to allow unit-testing of them instead. 
For manually testing RPC calls during development it's enough to use curl or any other tool that the particular developer prefers. Since test.py is not used in CI or integration tests, there is probably no need to have it in the codebase.
Comparing output of `clio` vs `rippled` should be done as part of integration testing done by QA.
