### ISSUE TITLE
Faulty response data on RPC POST

### ISSUE THREAD

**Issue by WietseWind** [XRPLF/clio#1050]
Hi 👋

When you send a POST to Clio without any data, the response isn't a regular JSON encoded error, but:
```
curl -X POST https://s2.ripple.com:51234/
```

Response:
```
Unable to parse request: incomplete JSON [boost.json:3 at 
/home/akremer/.conan/data/boost/1.82.0/_/_/package/
97ffea4cf7517387cd20d4bac15247eba29e9ead/include/
boost/json/basic_parser_impl.hpp:2754:17 in function 
'std::size_t boost::json::basic_parser<Handler>::write_some(
bool, const char*, std::size_t, boost::json::error_code&)']%
```

**Comment by kuznetsss** [comment]
Hi @WietseWind! Thanks for reporting the issue. We have already fixed the error message in #1037. But that's a good point that response is not a JSON data.

**Comment by godexsoft** [comment]
@WietseWind as Sergey responded above we already have fixed this (as much as we could). We are trying to stay compatible with `rippled` and `rippled` also does not return JSON errors in some cases.. we had to mimic this behaviour. This might eventually be fixed in both but it would have to be an API version update so it's not that simple.

Your original report on Mattermost spoke about two issues. The first one was this error message that is now fixed. And the other issue you mentioned was something wrong with the response from `submit` which is forwarded by Clio. Can you please update this issue (or create a new one) with as much detail as possible about the `submit` fails you were seeing? Thanks

**Comment by godexsoft** [comment]
Closing this one. Following `rippled` format as close as possible.
