### ISSUE TITLE
forwarded  is in the result  of response for error cases and out of result  for others.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#1091]
Request:
```json
{
    "method": "channel_authorize",
    "params": [{
        "channel_id": "42AC583481E3CA98F8918A7616D333D473FD66C3807BFB10D6348AA97E3E8C3",
        "secret": "ssRbYZ4kH5KTRDjyJHLyTam38F3G8",
        "amount": "1000000"
    }]
}
```

Error response:
```json
{
    "result": {
        "error": "channelMalformed",
        "error_code": 45,
        "error_message": "Payment channel is malformed.",
        "request": {
            "amount": "1000000",
            "channel_id": "42AC583481E3CA98F8918A7616D333D473FD66C3807BFB10D6348AA97E3E8C3",
            "command": "channel_authorize",
            "secret": "<masked>"
        },
        "status": "error",
        "type": "response",
        "forwarded": true
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

Request:
```json
{
    "method": "account_info",
    "params": [
        {
            "account": "rsrLLg3JKHVnXinfv79Rz8NKhze9cra63o",
            "strict": true,
            "ledger_index": "current",
            "queue": true
        }
    ]
}
```

Success response:
```json
{
    "result": {
        "account_data": {
            "Account": "rsrLLg3JKHVnXinfv79Rz8NKhze9cra63o",
            "Balance": "9999999990",
            "Flags": 0,
            "LedgerEntryType": "AccountRoot",
            "OwnerCount": 0,
            "PreviousTxnID": "00D0125819DB63A9943A7EB81347D692CD014C2AC2FA253F41EC4D8801835F91",
            "PreviousTxnLgrSeq": 2685069,
            "Sequence": 2685048,
            "index": "73E0C8B540AB5C1FDE8BDB9F5BA7954FD981BE36360E4E380940DE84F9A60BD7"
        },
        "account_flags": {
            "allowTrustLineClawback": false,
            "defaultRipple": false,
            "depositAuth": false,
            "disableMasterKey": false,
            "disallowIncomingCheck": false,
            "disallowIncomingNFTokenOffer": false,
            "disallowIncomingPayChan": false,
            "disallowIncomingTrustline": false,
            "disallowIncomingXRP": false,
            "globalFreeze": false,
            "noFreeze": false,
            "passwordSpent": false,
            "requireAuthorization": false,
            "requireDestinationTag": false
        },
        "ledger_current_index": 3220633,
        "queue_data": {
            "txn_count": 0
        },
        "validated": false,
        "status": "success"
    },
    "status": "success",
    "type": "response",
    "forwarded": true,
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

**Comment by godexsoft** [comment]
Can you please share the requests that lead to this? Thanks

**Comment by mounikakun** [comment]
Updated the comment.

**Comment by godexsoft** [comment]
Can you provide actual JSON requests and responses please? (i.e. ones with double quotes like the second pair). The first one is not a valid request/response from Clio.

**Comment by mounikakun** [comment]
yeah that one was from test run. it's just double quotes but let me update it.

**Comment by mounikakun** [comment]
Updated now.

**Comment by godexsoft** [comment]
Thanks. Now it makes sense. `tx_json` was not even a valid API 👍  
I can reproduce the issue. I'm not sure if this is something we can change as I suspect this behaviour have been there since forever but we will check and see if maybe it is a bug. 

According to your tests, have we just not seen this before or is it something new?

**Comment by mounikakun** [comment]
It's not new. But with existing validation, response from only successful txn is getting tested. So I would like to check if we can modify to keep it generic. Otherwise I will add extra validation to cover error cases too.

**Comment by godexsoft** [comment]
I think the logic for forwarded responses is this:
- If a response had an error on `rippled` side, we keep `error*`, `type` and `status` inside the `result` because that's what we got from `rippled`. Note that we currently don't add any of those to the top level, presumably not to confuse users. From Clio's perspective the request was handled successfully, it's `rippled` that send us an "error".
- If the response was successful, Clio will keep the entire original `rippled` response inside `result` but also add Clio's own `status` and `type` fields next to `result`. Not sure why it's not consistent with the error case tbh.
- The `forwarded` flag is special, Clio injects it into the `result` when forwarding and so the final location will depend on whether we got an error or success back from `rippled`. I think this is incorrect and `forwarded` should always be at the top. Note that forwarding always happens through WS API under the hood.

There is also a difference in format between WS and HTTP RPC. 

Personally, I think there should not be much harm in removing `forwarded` from `result` and just adding it back at the top on all paths. While this can be viewed as an API change, it's a Clio-specific flag and this change would not affect parity with `rippled`.
We could also discuss whether adding Clio's `status` and `type` at the top level of a forwarded error would be more, or less confusing. I'd argue that consistency is a good thing and therefore we should have those on all paths.

Forwarding format is not document in any detail on xrpl.org. It's only briefly mentioned [here](https://xrpl.org/the-clio-server.html#the-clio-server).

What do you think @cindyyan317 @kuznetsss @mounikakun @intelliot @kennyzlei ?
Perhaps @cjcobb23 can chip in with some ideas too.

**Comment by cindyyan317** [comment]
I think it makes more sense to move the "forwarded" outside the result , just let the result contains what returns from rippled. I tend to believe this is a bug.  From this [page](https://xrpl.org/response-formatting.html#response-formatting), we can see the "result" should be at the same level with "forwarded".  
Clio's status for "forwarded" response will be always "success" . I think it will be confusing if inner status is "error" while outside status is "success".

**Comment by godexsoft** [comment]
It does look like a bug indeed. And with the page you found, even more so! 👍 It must have been lingering for a while now. Seems like we did not have tests for the error case either.

**Comment by mounikakun** [comment]
Yeah we do have tests but as forwarded will be only in the clio response that was added to ignore parameters list. That's why the issue was not found till I checked it manually. As the fix was merged, will merge the validation for forwarded parameter.
