### ISSUE TITLE
Testnet NFTs unavailable

### ISSUE THREAD

**Issue by desimmons** [XRPLF/clio#1126]
It looks like no NFTs can be viewed through Ripple's testnet clio node.

E.g, I'm looking at this account (https://testnet.xrpl.org/accounts/rMk8Y88QsU4dmZTs5nYe8T4NfDsRz3CRfv/assets/nft)

which has a bunch of NFTs. You can see that the testnet.xrpl.org client fails to find them. Also the following fails in the same way:
```
echo '{"command":"nft_info","api_version":2,"nft_id":"000801F4E3AA6C75533DE712AB7C867450638E942395C21A0000099B00000000","id":{"_WsClient":1}}' | websocat -v wss://clio.altnet.rippletest.net:51233/

{"error":"objectNotFound","error_code":92,"error_message":"NFT not found","status":"error","type":"response","id":{"_WsClient":1},"request":{"command":"nft_info","api_version":2,"nft_id":"000801F4E3AA6C75533DE712AB7C867450638E942395C21A0000099B00000000","id":{"_WsClient":1}},"warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}
```

Note, making a `nft_history` call instead seems to give a success response, but the transaction array is empty.

This issue appears to be a problem across all minted NFTs AFAICT

**Comment by godexsoft** [comment]
Thanks for reporting this. We are looking into it 👍

**Comment by godexsoft** [comment]
@desimmons we tracked down the problem to the settings of the database of the public `altnet` Clio. 
The solution is to recreate the database with the correct settings and reimport the data. 
I will keep this issue open until the problem is resolved. Luckily this is not a bug in Clio's code 🙌 
Once again Thank You very much for reporting this ❤️

**Comment by desimmons** [comment]
@godexsoft thanks for such a quick turn around time! Will all previously minted NFTs be visible, or will only newly minted ones be visible?

**Comment by godexsoft** [comment]
@desimmons I actually don't know yet how this will be handled by the responsible infra team. I can update this issue once I find out.

**Comment by godexsoft** [comment]
@desimmons from what I heard, the database setting is now corrected and any new transactions and minted NFTs should not be missing. However, your original NFTs are gone for the time being from Clio's history on `altnet` (as well as potentially anything older than 24h from right now).
The infra team is going to recreate the database from scratch in order to restore all data that got lost due to the misconfiguration and once that process is finished we should have all data back, including your previously minted NFTs. This may take anywhere between few days to a couple of weeks. Since this is a test network I hope this is not a big issue for you and you can simply mint new NFTs which now should be persisted correctly. Let me know if there is anything else we can help with 👍
