### ISSUE TITLE
[amm_info] with malformed account error differs with rippled

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#1157]
Clio returns `actMalformed` whereas rippled returns `invalidParams` error

Request:
```json
{
  "method": "amm_info",
  "params": [
    {
      "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8"
    }
  ]
}
```
Rippled response:
```json
{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "Invalid parameters.",
        "ledger_current_index": 3899929,
        "request": {
            "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8",
            "command": "amm_info"
        },
        "status": "error",
        "validated": false
    }
}
```

Clio response:
```json
{
    "result": {
        "error": "actMalformed",
        "error_code": 35,
        "error_message": "Account malformed.",
        "status": "error",
        "type": "response",
        "request": {
            "method": "amm_info",
            "params": [
                {
                    "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8"
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        },
        {
            "id": 2002,
            "message": "This server may be out of date"
        }
    ]
}
```

**Comment by godexsoft** [comment]
This is a `rippled` inconsistency. Clio does not include `ledger_hash` and `ledger_index` in error responses. 
Neither does `rippled` for most APIs. This appears to be an oversight on `rippled`'s `amm_info` implementation.

I suggest we update the docs instead specifying that `ledger_hash`, `ledger_index` and `ledger_index_current` may be omitted in error responses.
We can leave `rippled`'s implementation as-is since those fields could be considered "extra" fields in the output which is not an API breakage.

**Comment by godexsoft** [comment]
This is caused by a difference in how `rippled` validates input compared to Clio.

Unfortunately, there is no _proper_ fix for us to apply here to get parity. One way to "fix" would be to move validation logic for `account` into the `process` function of the handler and don't validate it in the validation step that is described by a `spec`. Of course that would be a step backwards so we don't want to do that.

While we could easily fix the exact case reported in this issue, we can't solve the general case. For example this request would still produce different error code/message:
```json
{
  "method": "amm_info",
  "params": [
    {
      "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8",
      "amm_account" : "rLL58S26SjzyzmUoc65Cd1MvkpQk74ae4H"
    }
  ]
}
```

Another way to achieve parity would be to fix this on `rippled` side among other things that seem to be incorrect for `amm_info` such as `ledger_hash`, `ledger_index` and/or `ledger_current_index` appearing in error responses - something that does not happen for other APIs even in `rippled`. 

@Bronek what do you think about this?

**Comment by godexsoft** [comment]
Currently `rippled` returns inconsistent error code for the same invalid account for the input fields `account` and `amm_account`:

```
$ curl -d '{
  "method": "amm_info",
  "params": [
    {
      "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8"
    }
  ]
}'

{
  "result": {
    "error": "invalidParams",
    "error_code": 31,
    "error_message": "Invalid parameters.",
    "ledger_current_index": 4000379,
    "request": {
      "account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8",
      "command": "amm_info"
    },
    "status": "error",
    "validated": false
  }
}

$ curl -d '{
  "method": "amm_info",
  "params": [
    {
      "amm_account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8"
    }
  ]
}'

{
  "result": {
    "error": "actMalformed",
    "error_code": 35,
    "error_message": "Account malformed.",
    "ledger_current_index": 4000381,
    "request": {
      "amm_account": "rP32Fk3eRYDNSz8B31CxC5Jphc8Tz6Gt8",
      "command": "amm_info"
    },
    "status": "error",
    "validated": false
  }
}
```

**Comment by Bronek** [comment]
@gregtatcam do you think that's something we ought to change in `rippled` ?

**Comment by gregtatcam** [comment]
> @gregtatcam do you think that's something we ought to change in `rippled` ?

It makes sense to have a consistent error.

**Comment by Bronek** [comment]
I think this is because in `rippled` we **first** execute this check: 

```
        if ((params.isMember(jss::asset) != params.isMember(jss::asset2)) ||
            (params.isMember(jss::asset) == params.isMember(jss::amm_account)))
            return Unexpected(rpcINVALID_PARAMS);
```

In this case indeed both `asset` and `amm_account` are missing, so we return `rpcINVALID_PARAMS` before checking the `account`.

I wonder if we could push this check down.

**Comment by Bronek** [comment]
I will prepare a PR to change the order of checks in `rippled` for API version 3. As for API version 2 I think we just need to document the discrepancy and live with it

**Comment by godexsoft** [comment]
Fixed on rippled side.
