### ISSUE TITLE
Refactor Config

### ISSUE THREAD

**Issue by kuznetsss** [XRPLF/clio#1184]
It would be nice to refactor `Config` class to parse file once into structure applying all the default values and then use the structure everywhere in the code.

It will also allow us to easily add `--check-config` run option to verify provided config instead of starting Clio.

**Comment by godexsoft** [comment]
If we want to support live reload of some components in the future (such as DOSGuard for example) we might want to do a bit more than a plain `structure`. I'd like to be able to subscribe to changes of certain config sections so that we don't need to reload all components, only ones affected by the config change. Not sure how desired this functionality is, just an idea.

**Comment by kuznetsss** [comment]
I will create a separate task for live config reload.

In this task we want to rewrite config so it has these features:
- checking whether config file is valid
- generating default config (probably with something like `<required>` in place where there is no default value and the value is always required)

Some details of implementation:
- all the default values and values restrictions should be in one place inside implementation
- provided file should be parsed once into in-memory representation of config and only the representation should be used
- implementing this we should keep in mind that we want to support yaml in the future, so adding another parser should be easy

**Comment by kuznetsss** [comment]
We should create a separate issues for these items:
- checking whether config file is valid (`clio-server --verify-config`)
- generating default config (probably with something like <required> in place where there is no default value and the value is always required)
