### ISSUE TITLE
Embedded database as default 

### ISSUE THREAD

**Issue by RichardAH** [XRPLF/clio#190]
If you want people beyond experienced sysadmins to use Clio I strongly suggest including an embedded database as the default storage option. Most people are not going to have the time or ability to setup and maintain a third party database just for serving RPC, and they will not know what to do if something goes wrong with that database either (eg crash recovery scenario.)

**Comment by cjcobb23** [comment]
How would an embedded database scale horizontally? Horizontal scaling is one of the main reasons behind the whole clio design. I hear you that we want to make it simple, and I'd like to have another option besides Cassandra/Scylla, but I don't think embedded is the right idea. I'd rather revisit Postgres support. It's pretty easy to run Postgres.

**Comment by RichardAH** [comment]
>How would an embedded database scale horizontally?

The same way we scale rippled horizontally now? Just add more (Clio) nodes and use a load balancer.

If you want to support horizontal scaling better, then allow nodes to stagger what history they hold and then route based on the ledger index of the request.

I don't understand why you are trying to outsource horizontal scaling to a third party database instead of making it intrinsic to Clio? (i.e. making it what Clio actually does?) Isn't this the whole point of the project? To provide RPC scaling?

Clio could/should also provide load balancing between Clio servers / instances and history sharing between instances.

**Comment by cjcobb23** [comment]
One of the points of clio was to improve the horizontal scaling properties of rippled. Having to copy an entire database in order to spin up a new node is quite burdensome, and ends up using a lot of disk space if you are using many nodes (for example, if you run 30 nodes, you need 30 copies of the same data). Versus when we use Cassandra, we can spin up more clio nodes much more quickly, without having to copy any data, and without having to store the same data so many times. 

Another benefit to separating the database from the nodes is only one clio node needs to actually extract data from rippled and write to the database, and the rest can just be read only. With an embedded database, every clio node would need to extract data from rippled, requiring more rippled nodes, more redundant work by the clio nodes and would put more load on rippled. One of the key priorities of the project is to remove load from rippled.

I don't really see an issue with using a third party database? We don't need to reinvent the wheel. Cassandra has really useful scaling, availability and consistency features that work out of the box. Why not use it?

I would like to add support for an embedded database though. I was thinking of experimenting with SQLite, or maybe leveldb. I don't think this would be preferred for clusters with extremely high traffic, like s2 or xrplcluster, because of what I said above. But I think it would be nice for users with less traffic who only need to run a single node. Still, if we add the embedded database as a backend option, obviously the high traffic services could choose to just run many clio nodes with redundant copies of the same data, if that ends up being easier for them.

I don't think history sharing between instances should occur within clio itself. I think it would be better for that to happen via a proxy layer, that is aware of what clio servers have what data.

**Comment by RichardAH** [comment]
If you have 30 clio nodes that all point to the same database you haven't achieved horizontal scaling. Adding more clio nodes does not scale here. Using a database cluster and adding more clio and more database nodes at the same time _might_ achieve horizontal scaling. It's unlikely to be unlimited horizontal scaling.

For horizontal scaling you _want_ clio to own and fetch its own data so you _can_ simply add more clio nodes and thus more capacity. Each clio instance doesn't need the whole data set, as long as it has peers and it knows what data they have and that it can reroute requests for data it doesn't have to them.

Also: there is a reason rippled has NuDB. The amount and type of data we have is not really suited for out of the box rdbms or nosql products (as you discovered with postgres). Until Clio has data ownership (not outsourcing it to a third product server) I suspect it will remain fragile and unreliable. Perhaps I am wrong, time will tell.

**Comment by cjcobb23** [comment]
You can scale by adding more clio nodes if your database is not at capacity. If your database is at capacity, you can scale by adding nodes to your database. If both happen to be at capacity at the same time, you scale both. This is horizontal scaling.

@RichardAH I am getting the sense that you object to having to manage two pieces of software instead of just one (clio and cassandra/scylla, versus just clio). Is that correct? This is a fair criticism, and I do plan to look into an option for an embedded database, for this reason. But let's be clear: this is an operational issue, as opposed to a performance/scaling issue. 

The goal of clio was to make RPC scalable like a web service. A split architecture with software for handling requests talking to an independently scalable database is pretty standard for web services. A web service where each node has a full copy of the dataset stored in a local embedded database would be non-standard, and your proposed peering/routing solution even more non-standard.

**Comment by RichardAH** [comment]
> The goal of clio was to make RPC scalable like a web service. A split architecture with software for handling requests talking to an independently scalable database is pretty standard for web services. A web service where each node has a full copy of the dataset stored in a local embedded database would be non-standard, and your proposed peering/routing solution even more non-standard.

You’re building a traditional client-server model to serve already decentralised and distributed data that already lives on a peer to peer network as a solution to a scaling issue which is purely an implementation issue in rippled. A peering model should always be preferred here. The network design already scales, the data distribution already scales. It just comes down to writing a peer type to serve these workloads properly, it will scale naturally.

It’s your project you can write it how you like, these are just my thoughts.

**Comment by cjcobb23** [comment]
Why should a peering model always be preferred? I'm confused why you think anything about the way that RPC is handled by rippled today scales. I think the past several years have shown that it has not, with all of the performance and stability issues we have observed. We have been trying to do what you suggest, just run a bunch of rippled nodes, since the data is already decentralized and distributed, but that has not been working well at all.

**Comment by RichardAH** [comment]
> Why should a peering model always be preferred? I'm confused why you think anything about the way that RPC is handled by rippled today scales. I think the past several years have shown that it has not, with all of the performance and stability issues we have observed. We have been trying to do what you suggest, just run a bunch of rippled nodes, since the data is already decentralized and distributed, but that has not been working well at all.

I am curious what steps you have taken to fix the lock contention in rippled rpc layer

**Comment by cjcobb23** [comment]
A few other people are working on that. There is massive contention around the cache lock.

However, I don't think fixing this would make rippled suitable for web service level scale RPC handling. The fact that rippled needs to maintain sync with the network to be usable, and will inevitably desync under heavy load, makes the server unsuitable for heavy RPC traffic. Not only does this negatively affect any service using rippled for RPC handling, this would also negatively impact the peer network as a whole; desyncing peers have a ripple effect, and make it harder for other nodes to stay in sync as well. This alone makes rippled unsuitable for heavy RPC traffic.

Even if we did assume rippled stayed in sync at all times, using rippled for a high traffic RPC service has other problems.

First, whenever spinning up a new machine to scale horizontally, one must copy the entire database before the new node comes online. For rippled full history, that's 18TB. This takes a long time, and given that rippled requires an NVME drive, it's hard to even provision such a machine, not to mention expensive. Whereas with our current clio architecture, where the database is accessible over the network, the node can come online immediately, as soon as the binary is on the machine. This is a huge advantage when it comes to horizontal scaling.

Second, since rippled needs to do a significant amount of other work besides handle RPCs, a large cluster of rippled nodes deployed only for RPC handling is extremely wasteful and inefficient. You would need so much extra CPU and RAM for the non-RPC things rippled does (transaction processing, consensus, etc.), which, in the context of an RPC cluster, you don't actually care about. But you are forced to provision and pay for those resources. It's straight up expensive.

Clio is super lightweight. We use about 6GB of RAM at rest, and I have never seen the server go over 16GB even when handling over 1000 requests per second. Rippled nodes under a similar RPC load use almost an order of magnitude more RAM. This is because Clio only handles RPCs and is thus heavily optimized for that task and able to do it better than rippled.

Clio also uses way less disk to store the data than rippled. 3TB versus 18TB. This is a massive advantage, in terms of efficiency and cost.

So, in summary, using rippled for RPC handling requires so many more resources than Clio, in terms of disk, RAM and CPU. Not to mention rippled is not reliable for heavy RPC traffic because of the syncing behavior. Both of these things are unavoidable, regardless of implementation details and optimizations made to rippled. It's simply architectural.

I'd like to return to your idea of using an embedded database for clio. I agree operationally an embedded database would be easier, especially for small operators. And for this reason, I would like to add support for an embedded database. However, I don't think the embedded option is suitable for a heavy traffic RPC cluster, and here's why. These reasons are quite similar to everything I just said about rippled.

First, if an embedded database is used, adding a new node to the cluster requires first copying the database to the new node before said node can start handling traffic. While the Clio database is smaller than rippled's database, this is still a barrier to horizontal scaling, because you have to wait. Not to mention wasteful with a large cluster, as you will have so many copies of the same data and have to pay for all that disk. This would still apply even to your proposal of a sharded dataset. Most RPCs would hit the most recent shard, and so you'd still need to copy the most recent shard over before bringing the new node online, and would still need so many copies of the most recent shard. Compare this to the current Clio architecture, where we don't need to copy any data over before bringing a node online. It comes online as soon as the binary is on the machine.

Second, and I think more importantly, using an embedded database requires each clio node to extract data from rippled independently, a process that puts load on rippled. Adding a new clio node would then require either spinning up a new rippled node from which to extract data, or adding more load to an existing rippled node. A rippled node can only handle so many clio nodes extracting data, so inevitably one would need to spin up more rippled nodes when scaling horizontally. So, a cluster of Clio nodes each using an embedded database would require many more rippled nodes compared to our current architecture, where you only need a handful of rippled nodes, regardless of how many clio nodes you have. Adding more clio nodes never requires adding more rippled nodes. This problem applies to your sharded solution, because most RPCs hit the most recent shard, which needs to be constantly updated via ETL.

Having each clio node extract data from rippled is also quite wasteful in terms of CPU, since every clio node and rippled node would be doing the exact same work. Whereas with our current architecture, this work is done once, irrespective of how many Clio nodes are in the cluster.

So, in summary, using an embedded database for a large cluster of clio nodes cannot scale horizontally as easily as our current architecture because of the need for many more rippled nodes, as well as the need to copy the database before bringing a new node online and the redundant work and storage required of each new clio node. Such a setup would require much more disk, RAM and CPU, being much less efficient and much more expensive.

I do plan to add an embedded database, primarily for smaller operators. And you are obviously free to play around with it and build the solution you are describing using the embedded database option. But I just wanted to go into detail here about the scaling issues with an embedded database and why this is probably not the best solution for very large clusters. Hope this clears things up for you.

**Comment by RichardAH** [comment]
ok

**Comment by cjcobb23** [comment]
Reopening because I would like to add an embedded database option, for simple setups at the very least.

**Comment by godexsoft** [comment]
We will conduct investigations in the future and potentially add support for embedded DB. However, since this issue was created a new way to use cassandra that is very easy was found: `docker run --rm --name cassandra -d -p 9042:9042 cassandra:4.0.4`.
With this in mind we think there is no need for developers or even `people beyond experienced sysadmins` to know anything about installing cassandra anymore. Closing for now.
