### ISSUE TITLE
CPU monitoring and alerting for Cassandra and Clio application nodes

### ISSUE THREAD

**Issue by sophiax851** [XRPLF/clio#210]
From performance testing, both Cassandra and Clio application hosts are CPU bound, so we need to have them monitored and configured with alarms. We should also have spare capacity or strategy implemented when alert is triggered.

**Comment by cjcobb23** [comment]
For Cassandra, that's more of a devops thing and probably shouldn't exist within this repo.

For clio, the way to monitor this is probably the work queue length. If the work queue starts piling up, that means there is not enough available CPU. We should be able to add the work queue stats to `server_info` when the application refactor PR is merged.

**Comment by sophiax851** [comment]
Agreed. Once we fixed the issues with Cassandra and all of the other fixes you guys planned to make, and we come to a final configuration for Cassandra (e.g. availability zone vs. the 3 we have now etc.), I'll need to do some heavy load testing to help you to determine the relationship between work queue length and server capacity. Somehow I had an impression that queue length is more related to the type of calls than reflecting the congestion, e.g. ledger_data can easily make queue length grow but server may still have plenty capacity. I could be wrong. Also, we need to make sure we define a "period" before triggering the "load diverting" strategy to make sure we don't end up ping-ponging the calls to bring unnecessary instability.

**Comment by godexsoft** [comment]
Using `server_info` polling for monitoring is potentially dangerous due to the risk of being DDOSd which will render the rpc system partially useless for the duration of the attack and may result in inability of our polling mechanism to reach the queue length and other info from `server_info`.
What we suggest is to use something else. Maybe a file that `clio` periodically writes the required information into in a predefined format (like JSON) that we agree on. This will guarantee that these alerts can be read at all times regardless of RPC availability.

Let's discuss this outside of GH and once we have a plan we create the relevant tasks on GH.
