### ISSUE TITLE
"account_objects" request with parameter 'marker' returns "invalidParams" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#222]
Here is the sample request and response:
`{
  "method": "account_objects",
  "params": [
      {
          "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX",
          "deletion_blockers_only": false,
          "limit": 2,
          "validated": true,
          "marker": "77D55F149C997B7A15F683F9C568A2087DCEAD913962689F9E0A7A56E5F423C5,0"
      }
  ]
}`
 
 `{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "Malformed cursor",
        "status": "error",
        "type": "response",
        "request": {
            "method": "account_objects",
            "params": [
                {
                    "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX",
                    "deletion_blockers_only": false,
                    "limit": 2,
                    "validated": true,
                    "marker": "77D55F149C997B7A15F683F9C568A2087DCEAD913962689F9E0A7A56E5F423C5,0"
                }
            ]
        },
        "warnings": [
            "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        ]
    },
    "warnings": [
        "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request",
        "Too many requests"
    ]
}`

**Comment by natenichols** [comment]
So I think this is likely forwarded to rippled, which may use a different marker format, causing a "Malformed Cursor" error. 

It may be better to refactor the handlers in Clio and rippled to use the same format of marker

**Comment by cjcobb23** [comment]
can change markers in clio to match rippled

**Comment by cjcobb23** [comment]
It's debatable whether this is a bug. Markers are opaque values, that are just supposed to be blindly passed back to the server. They don't need to have any specific structure, and are only used for pagination. If rippled and clio have different markers, per the API documentation and description, that is entirely ok.

However, people do make HTTP requests to s2, and use markers, in which case the marker might be passed to a different server, which might be a rippled server, which uses different markers. This is bad practice, and something needs to be done to alleviate this. In this specific instance, we can probably make some changes to help their situation, but we can't always. Markers are server specific and should not be shared across servers.

This situation doesn't arise if clients connect over websocket, since the websocket pins them to a specific server. We could just say, if you are making a request that requires markers, you must connect to s2.ripple.com via websocket.

**Comment by cjcobb23** [comment]
Maybe we could even append a warning to every API response that includes a marker, and say something like "Markers are not shareable across different servers. Ensure your next request with the marker goes to this server"

**Comment by mounikakun** [comment]
Please correct me if I am wrong, here the issue is not about matching markers across servers. For `account_objects` with the marker generated from its previous response to retrieve objects is throwing error.

Work around:
- Send request with limit parameter and get the `marker` from response
`{ "method": "account_objects", "params": [ { "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX", "deletion_blockers_only": false, "limit": 2, "validated": true } ] }`
- send request again with `marker` from previous response.
`{ "method": "account_objects", "params": [ { "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX", "deletion_blockers_only": false, "limit": 2, "validated": true, "marker": "77D55F149C997B7A15F683F9C568A2087DCEAD913962689F9E0A7A56E5F423C5,0" } ] }`

**Comment by cjcobb23** [comment]
I see. I am actually able to page through account objects without any problem. Is this account on devnet?

**Comment by mounikakun** [comment]
yes.

**Comment by mounikakun** [comment]
I think this is an intermittent issue but I am not sure about the cause.

`{ "method": "account_objects", "params": [ { "account": "rDC9SqKcDY8NsBt4QyV4m6sufqLVfbrgEj", "ledger_index":"validated", "limit": 10,"marker": "E5A0E359ACC94D1AE680CBB0A4238437546B304F26E5528EBCCAB11FA588682F,0" } ] }`

It's working fine with the above request.
