### ISSUE TITLE
Clio history backfilling

### ISSUE THREAD

**Issue by irerimwenda** [XRPLF/clio#470]
Hi,

With understanding that Clio cannot backfill previous history and it only moves forward in time, are there any recommended public ripple servers that one can use as an ETL source in the config file of Clio if I would want to start at an earlier `start_sequence` in which  a built rippled server does not have that specified ledger.

**Comment by godexsoft** [comment]
Hi @irerimwenda ! Thanks for reaching out.
Backfill is indeed not supported yet (#66). Your idea of using `start_sequence` is correct. However, there are no public servers that Ripple provides at this moment. Normally operators run their own `rippled` alongside `clio` to achieve the behaviour you are seeking.

**Comment by irerimwenda** [comment]
Thank you for the clarification @godexsoft. Are there plans underway to provide a public Clio server running on mainnet if one would want to query nft data from past ledgers?

**Comment by godexsoft** [comment]
Hi @irerimwenda , as far as i'm aware, unfortunately there are no plans for this yet. If there is enough demand there may be a future discussion however. I imagine if this happens some day it will be announced and documented on the project page too.
I believe there is some work in progress on creating a publicly available dump of the full history so that operators can download it and start using said history faster. If and once that becomes available we will make sure to document it on the project page for your convenience!

**Comment by irerimwenda** [comment]
I would be looking forward to this if it pushes through to become publicly available. This would be great especially in saving time when one wants to get past history quicker.
Thanks again @godexsoft
