### ISSUE TITLE
Compatibility with latest rippled build process

### ISSUE THREAD

**Issue by MaestroLegato** [XRPLF/clio#645]
Hi!
I wanted to run Clio with the AMM (from [this](https://github.com/XRPLF/rippled/pull/4294) PR). Normally I believe you could just change `/CMake/deps/rippled.cmake` to point to AMM branch (like done [here](https://github.com/XRPLF/clio/pull/429), but this was before the build process changes I believe). However now it fails compilation (can't find lz4):

```
CMake Error at build/_deps/rippled-src/CMakeLists.txt:76 (find_package):
  By not providing "Findlz4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lz4", but
  CMake did not find one.

  Could not find a package configuration file provided by "lz4" with any of
  the following names:

    lz4Config.cmake
    lz4-config.cmake

  Add the installation prefix of "lz4" to CMAKE_PREFIX_PATH or set "lz4_DIR"
  to a directory containing one of the above files.  If "lz4" provides a
  separate development package or SDK, be sure it has been installed.
```

This is not strictly related to AMM per se, same thing happens if you try to use e.g. mainnet rippled 1.10.1.

I, of course, could manually get lz4 and so on, but last time I was in a situation like this I was in a loop of manual package hunting for hours that led nowhere 😅 

I wonder if there is an easy way to satisfy all the deps in latest rippled versions while building Clio, or even to tell the build process to use conan to prepare rippled.

Worth noting that I have very rudimentary understanding of C++, so I don't really understand how it all connects together unfortunately. 🥲

**Comment by injaelee** [comment]
Heya @MaestroLegato, the [XRPLF/rippled](https://github.com/XRPLF/rippled) repository has migrated to the Conan Build System from CMake. Conan simplifies the dependency management simplifying the process of managing and integrating external libraries and dependencies; simplifies the cross-platform support; allows caching and sharing pre-compiled binary packages; integrates with CMake; and enables DevOps and continues integration out of the box.

Clio uses rippled as a library that requires compilation as part of the Clio build process. Since rippled has switched to using Conan, Clio builds must be kicked off using Conan so that the dependencies are properly managed for a successful build.

We will be estimating the work, potentially, by the end of next week. Once we have an estimate we will update this thread.
