### ISSUE TITLE
[account_tx] with non existent account do not return an error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#651]
Request:
`{
    "method": "account_tx",
    "params": [
        {
            "account": "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj"
        }
    ]
}`

Response:
`{
    "result": {
        "account": "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj",
        "ledger_index_max": 28952659,
        "ledger_index_min": 23333389,
        "limit": 0,
        "status": "success",
        "transactions": [],
        "validated": true
    }
}`

**Comment by godexsoft** [comment]
`rippled` seems to return the same empty array as `clio` for this request. Maybe i'm misinterpreting the issue, please let me know what needs to be done, if anything @mounikakun 👍

**Comment by mounikakun** [comment]
Yes rippled do not throw error for non-existent account but Clio throws 'actNotFound' for all the requests with non_existent account. If we are going back and following rippled then there's no need to fix this issue.

@godexsoft if we are matching rippled response, please go ahead and close this issue.

**Comment by godexsoft** [comment]
This may have to mimic rippled and not throw the error after all. It's because in `rippled` it's computationally expensive to find whether an account exists or not. That's also why they are not returning the error in the first place. There is a discussion on `rippled`'s tracker but I think the outcome will be that it's best to leave it as is and mimic on Clio side.

**Comment by cindyyan317** [comment]
https://github.com/XRPLF/rippled/pull/4619 
We decide to keep sync with rippled for this one since it is expensive for rippled.
