### ISSUE TITLE
Add RPC/WS ports to server_info

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#797]
https://github.com/XRPLF/rippled/pull/4427

**Comment by godexsoft** [comment]
It looks like this is not very applicable to Clio actually. 
We don't have any ports to advertise:
- The ETL source ports, both gRPC and the ws/wss are already returned in `server_info` but only for *admin* users (coming from 127.0.0.1)
- The port of the Clio server itself is pointless to return in `server_info` because the client would have had to know it to request the `server_info` in the first place

cc @intelliot @injaelee

**Comment by intelliot** [comment]
Would it be useful to make Clio `/crawl`able? 

https://xrpl.org/peer-crawler.html

This would ensure Clio can (eventually) be a full replacement for rippled "reporting".

**Comment by godexsoft** [comment]
I'm not sure if it's applicable @intelliot , it looks like `/crawl` is for p2p nodes, not for reporting/clio. I don't immediately see a use case for this in Clio but maybe you can explain in more detail what use case you see.

**Comment by godexsoft** [comment]
Does not look like there is much interest in this. @intelliot i'm going to close this. Feel free to re-open if you disagree and have some more input on this. 👍
